---
#  \//||\/||
#  // ||  ||__
GUI:
  Theme:
    Background:     0x555555
    Forground:      0x888888
    Highlights:     0xaaaaaa
    text:           0xdddddd
  Dimensions:
    x:
    y:
  Position:
    x:
    y:
  Defaults:
    Dark theme: True
---
Presets:
  preset1:
  preset2:
  preset3:
History:
---
BASE_FOLDER: C:/Users/Barbf/Downloads/cmanwx
BASIS_YEAR: '2020'
BASIS_MONTH: '01'
MAX_FILES_TO_RUN: 1000
OUTPUT_YEARS:
  [2022, 2023, 2024, 2025]
OUTPUT_MONTHS:
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
MonthLength:
  [0,31,28,31,30,31,30,31,31,30,31,30,31]
statscolumns:
- FieldName
- DataType
- Min
- Max
- Mean
- StdDev
- Median
- Mode
- NumValues
- NumNulls
- NumUnique
- AutoCorr
- FFT
- Distrib
