---
BASE_FOLDER: C:/Users/Barbf/Downloads/cmanwx
BASIS_YEAR: '2020'
BASIS_MONTH: '10'
MAX_FILES_TO_RUN: 1
OUTPUT_YEARS:
- 2024
- 2025
- 2026
OUTPUT_MONTHS:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
MonthLength:
- 0
- 31
- 28
- 31
- 30
- 31
- 30
- 31
- 31
- 30
- 31
- 30
- 31
